Update .gitlab-ci.yml [skip ci]

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -9,12 +9,6 @@
 # * Verify but don't deploy merge requests.
 # * Deploy built artifacts from master branch only.
 
-#include:
-#  - template: Security/Dependency-Scanning.gitlab-ci.yml
-#  - template: Security/License-Scanning.gitlab-ci.yml
-#  - template: Security/SAST.gitlab-ci.yml
-#  - template: Security/Secret-Detection.gitlab-ci.yml
-
 variables:
   # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
   # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
@@ -22,7 +16,7 @@ variables:
   # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
   # when running from the command line.
   # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
-  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
+  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true clean"
 
 # This template uses jdk8 for verifying and deploying images
 image: maven:3.3.9-jdk-8
@@ -33,29 +27,59 @@ cache:
   paths:
     - .m2/repository
 
+stages:
+  - build  
+  - deploy
+  - test
+  - release
+
 # For merge requests do not `deploy` but only run `verify`.
 # See https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html
 .verify: &verify
-  stage: test
+  stage: build
   script:
-    - 'mvn $MAVEN_CLI_OPTS verify'
+    - 'mvn $MAVEN_CLI_OPTS install'
   except:
-    - master
+    variables:
+      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
 
 # Verify merge requests using JDK8
 verify:jdk8:
   <<: *verify
 
 # To deploy packages from CI, create a ci_settings.xml file
-# For deploying packages to GitLab's Maven Repository: See https://docs.gitlab.com/ee/user/project/packages/maven_repository.html#creating-maven-packages-with-gitlab-cicd for more details.
+# For deploying packages to GitLab's Maven Repository: See https://docs.gitlab.com/ee/user/packages/maven_repository/index.html#create-maven-packages-with-gitlab-cicd for more details.
 # Please note: The GitLab Maven Repository is currently only available in GitLab Premium / Ultimate.
 # For `master` branch run `mvn deploy` automatically.
 deploy:jdk8:
   stage: deploy
   script:
     - if [ ! -f ci_settings.xml ];
-        then echo "CI settings missing\! If deploying to GitLab Maven Repository, please see https://docs.gitlab.com/ee/user/project/packages/maven_repository.html#creating-maven-packages-with-gitlab-cicd for instructions.";
+        then echo "[ ERROR ]:CI settings missing\!"; exit 1;
       fi
     - 'mvn $MAVEN_CLI_OPTS deploy -s ci_settings.xml'
   only:
-    - master
+    variables:
+      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
+
+integrtaion_test:jdk8:
+  stage: test
+  script:
+    - 'mvn $MAVEN_CLI_OPTS test-compile failsafe:integration-test failsafe:verify'
+  rules:
+    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
+      when: manual
+
+release:jdk8:
+  stage: release
+  script:
+    - if [ ! -f ci_settings.xml ];
+        then echo "[ ERROR ]:CI settings missing\!"; exit 1;
+      fi ; 
+    - 'git config user.name ${GITLAB_USER_NAME}; git config user.email ${GITLAB_USER_EMAIL}'
+    - 'git checkout -B ${CI_DEFAULT_BRANCH}; ls -la'
+    - 'mvn $MAVEN_CLI_OPTS release:prepare -s ci_settings.xml'
+    - 'mvn $MAVEN_CLI_OPTS release:perform -s ci_settings.xml'
+  rules:
+    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $GITLAB_MAVEN_PRIVATE_TOKEN
+      when: manual
