before_script check for deploy integration and release [skip ci]

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -51,18 +51,20 @@ verify:jdk8:
 # For deploying packages to GitLab's Maven Repository: See https://docs.gitlab.com/ee/user/packages/maven_repository/index.html#create-maven-packages-with-gitlab-cicd for more details.
 # Please note: The GitLab Maven Repository is currently only available in GitLab Premium / Ultimate.
 # For `master` branch run `mvn deploy` automatically.
+before_script:
+  - if [ ! -f ci_settings.xml ];
+        then echo "[ ERROR ]:CI settings missing\!"; exit 1;
+      fi ;
+
 deploy:jdk8:
   stage: deploy
   script:
-    - if [ ! -f ci_settings.xml ];
-        then echo "[ ERROR ]:CI settings missing\!"; exit 1;
-      fi
     - 'mvn $MAVEN_CLI_OPTS deploy -s ci_settings.xml'
   only:
     variables:
       - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
 
-integrtaion_test:jdk8:
+integrataion_test:jdk8:
   stage: test
   script:
     - 'mvn $MAVEN_CLI_OPTS test-compile failsafe:integration-test failsafe:verify -s ci_settings.xml'
@@ -72,10 +74,7 @@ integrtaion_test:jdk8:
 
 release:jdk8:
   stage: release
-  script:
-    - if [ ! -f ci_settings.xml ];
-        then echo "[ ERROR ]:CI settings missing\!"; exit 1;
-      fi ; 
+  script: 
     - 'git config user.name ${GITLAB_USER_NAME}; git config user.email ${GITLAB_USER_EMAIL}'
     - 'git checkout -B ${CI_DEFAULT_BRANCH}; ls -la'
     - 'mvn $MAVEN_CLI_OPTS release:prepare -s ci_settings.xml'
